"""
Problem 2 - Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

x = 1
y = 2
sum_ = 0

for i in range(4000):
	x, y = y, x + y

	if x % 2 == 0:
		sum_ += x

		if sum_ >= 4000000: # the first time sum_ exceedes 4000000, the for loop breaks
			break

	continue

print(sum_)